title: Santosh Yadav # your name (or website title) here
logo: "/images/Santosh Yadav.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Santosh Yadav Portfolio
  <br><br>
  Sr. Software Engineer 
  <br><br>
  <a href="https://www.linkedin.com/in/santosh-yadav-5855084/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
